// Entra ID configuration for Azure Operations Agent SPA
//
// Auto-generated by setup-app-registration.ps1
// App Registration: azure-ops-agent-spa

export const msalConfig = {
  auth: {
    clientId: "220a3110-0efd-4f1b-bbc0-3c4b43ed5e85",
    authority: "https://login.microsoftonline.com/common",
    redirectUri: window.location.origin,
  },
  cache: {
    cacheLocation: "sessionStorage",
    storeAuthStateInCookie: false,
  },
};

// Delegated scope — token is forwarded to backend which exchanges it via OBO
// for an Azure Management token
export const azureManagementLoginRequest = {
  scopes: ["api://220a3110-0efd-4f1b-bbc0-3c4b43ed5e85/access_as_user"],
};
